//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhPro.Oodd.Web.OrgService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rhpro.com.ar/", ConfigurationName="OrgService.ConsultasSoap")]
    public interface ConsultasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/VersionWS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VersionWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/Version", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Version(string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/Patch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Patch(string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/Link", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Link(string Usuario, string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/Mensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Mensaje(string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/Banner", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Banner(string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/Modulos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Modulos(string Usuario, string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/MRU", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable MRU(string Usuario, int Cant, string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/PagPie", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PagPie(string Usuario, string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/comboBase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable comboBase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Search(string Usuario, string Palabra, string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Login(string Usuario, string Pass, string SegNt, string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/CambiarPass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CambiarPass(string Usuario, string PassOld, string PassNew, string PassConfirm, string Base, string Idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/Padre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long Padre(long CodEmp, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/Hijos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Hijos(long CodEmp, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/DatosEmp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DatosEmp(long CodEmp, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/AsignarPadre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AsignarPadre(long CodPadre, long CodHijo, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/AsignarHijo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AsignarHijo(long CodHijo, long CodPadre, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/BorrarHijo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool BorrarHijo(long CodHijo, long CodPadre, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/BorrarPadre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool BorrarPadre(long CodHijo, long CodPadre, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/BuscarEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BuscarEmpleado(long Legajo, long Activo, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/SgtEmpl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SgtEmpl(long Legajo, long Activo, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/AntEmpl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AntEmpl(long Legajo, long Activo, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/EstadoPostulante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable EstadoPostulante(int tipoDoc, string Doc, int Sexo, string Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rhpro.com.ar/TablaPlana", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TablaPlana(string Tabla, string Base);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultasSoapChannel : RhPro.Oodd.Web.OrgService.ConsultasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultasSoapClient : System.ServiceModel.ClientBase<RhPro.Oodd.Web.OrgService.ConsultasSoap>, RhPro.Oodd.Web.OrgService.ConsultasSoap {
        
        public ConsultasSoapClient() {
        }
        
        public ConsultasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VersionWS() {
            return base.Channel.VersionWS();
        }
        
        public string Version(string Base, string Idioma) {
            return base.Channel.Version(Base, Idioma);
        }
        
        public string Patch(string Base, string Idioma) {
            return base.Channel.Patch(Base, Idioma);
        }
        
        public System.Data.DataTable Link(string Usuario, string Base, string Idioma) {
            return base.Channel.Link(Usuario, Base, Idioma);
        }
        
        public System.Data.DataTable Mensaje(string Base, string Idioma) {
            return base.Channel.Mensaje(Base, Idioma);
        }
        
        public System.Data.DataTable Banner(string Base, string Idioma) {
            return base.Channel.Banner(Base, Idioma);
        }
        
        public System.Data.DataTable Modulos(string Usuario, string Base, string Idioma) {
            return base.Channel.Modulos(Usuario, Base, Idioma);
        }
        
        public System.Data.DataTable MRU(string Usuario, int Cant, string Base, string Idioma) {
            return base.Channel.MRU(Usuario, Cant, Base, Idioma);
        }
        
        public System.Data.DataTable PagPie(string Usuario, string Base, string Idioma) {
            return base.Channel.PagPie(Usuario, Base, Idioma);
        }
        
        public System.Data.DataTable comboBase() {
            return base.Channel.comboBase();
        }
        
        public System.Data.DataTable Search(string Usuario, string Palabra, string Base, string Idioma) {
            return base.Channel.Search(Usuario, Palabra, Base, Idioma);
        }
        
        public System.Data.DataTable Login(string Usuario, string Pass, string SegNt, string Base, string Idioma) {
            return base.Channel.Login(Usuario, Pass, SegNt, Base, Idioma);
        }
        
        public string CambiarPass(string Usuario, string PassOld, string PassNew, string PassConfirm, string Base, string Idioma) {
            return base.Channel.CambiarPass(Usuario, PassOld, PassNew, PassConfirm, Base, Idioma);
        }
        
        public long Padre(long CodEmp, int Base) {
            return base.Channel.Padre(CodEmp, Base);
        }
        
        public System.Data.DataTable Hijos(long CodEmp, int Base) {
            return base.Channel.Hijos(CodEmp, Base);
        }
        
        public System.Data.DataTable DatosEmp(long CodEmp, int Base) {
            return base.Channel.DatosEmp(CodEmp, Base);
        }
        
        public bool AsignarPadre(long CodPadre, long CodHijo, int Base) {
            return base.Channel.AsignarPadre(CodPadre, CodHijo, Base);
        }
        
        public bool AsignarHijo(long CodHijo, long CodPadre, int Base) {
            return base.Channel.AsignarHijo(CodHijo, CodPadre, Base);
        }
        
        public bool BorrarHijo(long CodHijo, long CodPadre, int Base) {
            return base.Channel.BorrarHijo(CodHijo, CodPadre, Base);
        }
        
        public bool BorrarPadre(long CodHijo, long CodPadre, int Base) {
            return base.Channel.BorrarPadre(CodHijo, CodPadre, Base);
        }
        
        public System.Data.DataTable BuscarEmpleado(long Legajo, long Activo, int Base) {
            return base.Channel.BuscarEmpleado(Legajo, Activo, Base);
        }
        
        public System.Data.DataTable SgtEmpl(long Legajo, long Activo, int Base) {
            return base.Channel.SgtEmpl(Legajo, Activo, Base);
        }
        
        public System.Data.DataTable AntEmpl(long Legajo, long Activo, int Base) {
            return base.Channel.AntEmpl(Legajo, Activo, Base);
        }
        
        public System.Data.DataTable EstadoPostulante(int tipoDoc, string Doc, int Sexo, string Base) {
            return base.Channel.EstadoPostulante(tipoDoc, Doc, Sexo, Base);
        }
        
        public System.Data.DataTable TablaPlana(string Tabla, string Base) {
            return base.Channel.TablaPlana(Tabla, Base);
        }
    }
}
