
--Tabla para el reporte de seguros.

create table rep27(
repnro int IDENTITY (1, 1) NOT NULL ,
pliqnro int null,
pronro int null,
empresa int null,
proaprob int NOT NULL,
bpronro int not null,
Fecha datetime NOT NULL,
Hora varchar(10) NOT NULL,
iduser varchar(20) NOT NULL,
ternro int not null,
empleg int not null,
apeynom varchar(40) not null,
dlimonto dec(19,4) null,
tpanro1 int null,
tpanro2 int null,
tpanro3 int null,
tpanro4 int null,
concnro int null,
novsum dec(19,4) null,
liqsum dec(19,4) null,
novempcant int null,
liqempcant int null,
liqmonto dec(19,4) null,
tprocnro int null,
tconnro int null,
es_cant smallint null,
secdes varchar(25) null,
sucnro int null,
sumaprin dec(19,4) null,
nrodoc varchar(20) null,
tidnro int null,
columna1 dec(19,4) null,
columna2 dec(19,4) null,
columna3 dec(19,4) null,
columna4 dec(19,4) null,
columna5 dec(19,4) null
)