'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18052
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceSpec
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WSContainer", [Namespace]:="http://schemas.datacontract.org/2004/07/HTTPServers.WCFWebServer.WebServices")>  _
    Public Enum WSContainer As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Cycle = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Calendar = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Shift = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TimeType = 9
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        User = 11
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Zone = 12
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Terminal = 13
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Employee = 14
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Message = 15
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TimeSlot = 16
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ResultTemplate = 17
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FilterTemplate = 18
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        StructureTree = 22
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Result = 23
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Arithmetic = 24
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ActionGroup = 25
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ActionCalendar = 26
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Planning = 27
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Parent = 28
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Settings = 29
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TimeTypeType = 30
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        InconsistencyType = 32
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ConTypeMessage = 33
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ResultType = 34
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Reader = 35
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Card = 36
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BreakMethod = 37
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Menu = 38
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Sex = 39
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ConType = 40
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Alarm = 41
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [Module] = 42
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EventType = 43
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Fields = 45
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SystemResult = 46
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        InconsistencyResult = 47
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FieldView = 49
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Sessions = 50
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TerminalStatus = 51
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TimeZone = 52
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Door = 53
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Device = 54
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DeviceConnector = 55
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DeviceType = 56
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DetectedTerminal = 57
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Action = 58
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MessageDirection = 59
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ManualTransfer = 60
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TransferSource = 61
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HorizontalAlign = 62
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Chart = 63
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Custom = 64
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AlarmDefs = 65
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Primavera = 66
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Falta = 67
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        VisitState = 68
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ExportTemplate = 69
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AlarmInstance = 70
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EventAction = 71
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PermissionTemplate = 76
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AccessTemplate = 100
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Visit = 101
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        VisitCard = 102
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Report = 120
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WSElement", [Namespace]:="http://schemas.datacontract.org/2004/07/HTTPServers.WCFWebServer.WebServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WSElement
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataField As System.Collections.Generic.Dictionary(Of String, Object)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Data() As System.Collections.Generic.Dictionary(Of String, Object)
            Get
                Return Me.DataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataField, value) <> true) Then
                    Me.DataField = value
                    Me.RaisePropertyChanged("Data")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Result", [Namespace]:="http://schemas.datacontract.org/2004/07/HTTPServers.WCFWebServer.WebServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Result
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValuesField() As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property [Date]() As Date
            Get
                Return Me.DateField
            End Get
            Set
                If (Me.DateField.Equals(value) <> true) Then
                    Me.DateField = value
                    Me.RaisePropertyChanged("Date")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Values() As Integer()
            Get
                Return Me.ValuesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValuesField, value) <> true) Then
                    Me.ValuesField = value
                    Me.RaisePropertyChanged("Values")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClockingType", [Namespace]:="http://schemas.datacontract.org/2004/07/HTTPServers.WCFWebServer.WebServices")>  _
    Public Enum ClockingType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Attendance = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Access = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Visit = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SDK = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Clocking", [Namespace]:="http://schemas.datacontract.org/2004/07/HTTPServers.WCFWebServer.WebServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Clocking
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CardNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClockingTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatetimeField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdClockingField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdEmployerField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdReaderField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTerminalField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTimeTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdZoneField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CardNumber() As String
            Get
                Return Me.CardNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CardNumberField, value) <> true) Then
                    Me.CardNumberField = value
                    Me.RaisePropertyChanged("CardNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClockingType() As Integer
            Get
                Return Me.ClockingTypeField
            End Get
            Set
                If (Me.ClockingTypeField.Equals(value) <> true) Then
                    Me.ClockingTypeField = value
                    Me.RaisePropertyChanged("ClockingType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Datetime() As Date
            Get
                Return Me.DatetimeField
            End Get
            Set
                If (Me.DatetimeField.Equals(value) <> true) Then
                    Me.DatetimeField = value
                    Me.RaisePropertyChanged("Datetime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IP() As String
            Get
                Return Me.IPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IPField, value) <> true) Then
                    Me.IPField = value
                    Me.RaisePropertyChanged("IP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdClocking() As Integer
            Get
                Return Me.IdClockingField
            End Get
            Set
                If (Me.IdClockingField.Equals(value) <> true) Then
                    Me.IdClockingField = value
                    Me.RaisePropertyChanged("IdClocking")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdEmployer() As Integer
            Get
                Return Me.IdEmployerField
            End Get
            Set
                If (Me.IdEmployerField.Equals(value) <> true) Then
                    Me.IdEmployerField = value
                    Me.RaisePropertyChanged("IdEmployer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdReader() As Integer
            Get
                Return Me.IdReaderField
            End Get
            Set
                If (Me.IdReaderField.Equals(value) <> true) Then
                    Me.IdReaderField = value
                    Me.RaisePropertyChanged("IdReader")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTerminal() As Integer
            Get
                Return Me.IdTerminalField
            End Get
            Set
                If (Me.IdTerminalField.Equals(value) <> true) Then
                    Me.IdTerminalField = value
                    Me.RaisePropertyChanged("IdTerminal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTimeType() As Integer
            Get
                Return Me.IdTimeTypeField
            End Get
            Set
                If (Me.IdTimeTypeField.Equals(value) <> true) Then
                    Me.IdTimeTypeField = value
                    Me.RaisePropertyChanged("IdTimeType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdZone() As Integer
            Get
                Return Me.IdZoneField
            End Get
            Set
                If (Me.IdZoneField.Equals(value) <> true) Then
                    Me.IdZoneField = value
                    Me.RaisePropertyChanged("IdZone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Source() As Integer
            Get
                Return Me.SourceField
            End Get
            Set
                If (Me.SourceField.Equals(value) <> true) Then
                    Me.SourceField = value
                    Me.RaisePropertyChanged("Source")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property State() As Integer
            Get
                Return Me.StateField
            End Get
            Set
                If (Me.StateField.Equals(value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property User() As String
            Get
                Return Me.UserField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserField, value) <> true) Then
                    Me.UserField = value
                    Me.RaisePropertyChanged("User")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceSpec.IWebServiceContract")>  _
    Public Interface IWebServiceContract
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/List", ReplyAction:="http://tempuri.org/IWebServiceContract/ListResponse")>  _
        Function List(ByVal container As ServiceSpec.WSContainer) As ServiceSpec.WSElement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/ListFields", ReplyAction:="http://tempuri.org/IWebServiceContract/ListFieldsResponse")>  _
        Function ListFields(ByVal container As ServiceSpec.WSContainer, ByVal fields() As String, ByVal filter As String) As ServiceSpec.WSElement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/Get", ReplyAction:="http://tempuri.org/IWebServiceContract/GetResponse")>  _
        Function [Get](ByVal container As ServiceSpec.WSContainer, ByVal id As Integer) As ServiceSpec.WSElement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/GetFields", ReplyAction:="http://tempuri.org/IWebServiceContract/GetFieldsResponse")>  _
        Function GetFields(ByVal container As ServiceSpec.WSContainer, ByVal id As Integer, ByVal fields() As String) As ServiceSpec.WSElement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/Set", ReplyAction:="http://tempuri.org/IWebServiceContract/SetResponse")>  _
        Function [Set](ByVal container As ServiceSpec.WSContainer, ByVal element As ServiceSpec.WSElement) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/Delete", ReplyAction:="http://tempuri.org/IWebServiceContract/DeleteResponse")>  _
        Function Delete(ByVal container As ServiceSpec.WSContainer, ByVal id As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/GetResults", ReplyAction:="http://tempuri.org/IWebServiceContract/GetResultsResponse")>  _
        Function GetResults(ByVal employeeId As Integer, ByVal firstDate As Date, ByVal lastDate As Date) As ServiceSpec.WSElement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/Results", ReplyAction:="http://tempuri.org/IWebServiceContract/ResultsResponse")>  _
        Function Results(ByVal employeeId As Integer, ByVal type As String, ByVal firstDate As Date, ByVal lastDate As Date, ByVal resultsNames() As String) As ServiceSpec.Result()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/Clockings", ReplyAction:="http://tempuri.org/IWebServiceContract/ClockingsResponse")>  _
        Function Clockings(ByVal employeeId As Integer, ByVal firstDate As Date, ByVal lastDate As Date, ByVal type As ServiceSpec.ClockingType) As ServiceSpec.Clocking()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/GetTimeSlot", ReplyAction:="http://tempuri.org/IWebServiceContract/GetTimeSlotResponse")>  _
        Function GetTimeSlot(ByVal employeeId As Integer, ByVal readerId As Integer, ByVal day As Date) As ServiceSpec.WSElement
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/SetTimeSlot", ReplyAction:="http://tempuri.org/IWebServiceContract/SetTimeSlotResponse")>  _
        Function SetTimeSlot(ByVal employeeId As Integer, ByVal startDay As Date, ByVal endDay As Date, ByVal readerId As Integer, ByVal timeSlots As ServiceSpec.WSElement) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/AddPlanning", ReplyAction:="http://tempuri.org/IWebServiceContract/AddPlanningResponse")>  _
        Function AddPlanning(ByVal employeeId As Integer, ByVal planningName As String, ByVal allDay As Boolean, ByVal startMinute As Integer, ByVal endMinute As Integer, ByVal timeTypeId As Integer, ByVal dateInterval() As Date) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWebServiceContract/GetDateRange", ReplyAction:="http://tempuri.org/IWebServiceContract/GetDateRangeResponse")>  _
        Function GetDateRange(ByVal dateList() As Date) As ServiceSpec.WSElement
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWebServiceContractChannel
        Inherits ServiceSpec.IWebServiceContract, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebServiceContractClient
        Inherits System.ServiceModel.ClientBase(Of ServiceSpec.IWebServiceContract)
        Implements ServiceSpec.IWebServiceContract
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function List(ByVal container As ServiceSpec.WSContainer) As ServiceSpec.WSElement Implements ServiceSpec.IWebServiceContract.List
            Return MyBase.Channel.List(container)
        End Function
        
        Public Function ListFields(ByVal container As ServiceSpec.WSContainer, ByVal fields() As String, ByVal filter As String) As ServiceSpec.WSElement Implements ServiceSpec.IWebServiceContract.ListFields
            Return MyBase.Channel.ListFields(container, fields, filter)
        End Function
        
        Public Function [Get](ByVal container As ServiceSpec.WSContainer, ByVal id As Integer) As ServiceSpec.WSElement Implements ServiceSpec.IWebServiceContract.[Get]
            Return MyBase.Channel.Get(container, id)
        End Function
        
        Public Function GetFields(ByVal container As ServiceSpec.WSContainer, ByVal id As Integer, ByVal fields() As String) As ServiceSpec.WSElement Implements ServiceSpec.IWebServiceContract.GetFields
            Return MyBase.Channel.GetFields(container, id, fields)
        End Function
        
        Public Function [Set](ByVal container As ServiceSpec.WSContainer, ByVal element As ServiceSpec.WSElement) As Integer Implements ServiceSpec.IWebServiceContract.[Set]
            Return MyBase.Channel.Set(container, element)
        End Function
        
        Public Function Delete(ByVal container As ServiceSpec.WSContainer, ByVal id As Integer) As Boolean Implements ServiceSpec.IWebServiceContract.Delete
            Return MyBase.Channel.Delete(container, id)
        End Function
        
        Public Function GetResults(ByVal employeeId As Integer, ByVal firstDate As Date, ByVal lastDate As Date) As ServiceSpec.WSElement Implements ServiceSpec.IWebServiceContract.GetResults
            Return MyBase.Channel.GetResults(employeeId, firstDate, lastDate)
        End Function
        
        Public Function Results(ByVal employeeId As Integer, ByVal type As String, ByVal firstDate As Date, ByVal lastDate As Date, ByVal resultsNames() As String) As ServiceSpec.Result() Implements ServiceSpec.IWebServiceContract.Results
            Return MyBase.Channel.Results(employeeId, type, firstDate, lastDate, resultsNames)
        End Function
        
        Public Function Clockings(ByVal employeeId As Integer, ByVal firstDate As Date, ByVal lastDate As Date, ByVal type As ServiceSpec.ClockingType) As ServiceSpec.Clocking() Implements ServiceSpec.IWebServiceContract.Clockings
            Return MyBase.Channel.Clockings(employeeId, firstDate, lastDate, type)
        End Function
        
        Public Function GetTimeSlot(ByVal employeeId As Integer, ByVal readerId As Integer, ByVal day As Date) As ServiceSpec.WSElement Implements ServiceSpec.IWebServiceContract.GetTimeSlot
            Return MyBase.Channel.GetTimeSlot(employeeId, readerId, day)
        End Function
        
        Public Function SetTimeSlot(ByVal employeeId As Integer, ByVal startDay As Date, ByVal endDay As Date, ByVal readerId As Integer, ByVal timeSlots As ServiceSpec.WSElement) As Boolean Implements ServiceSpec.IWebServiceContract.SetTimeSlot
            Return MyBase.Channel.SetTimeSlot(employeeId, startDay, endDay, readerId, timeSlots)
        End Function
        
        Public Function AddPlanning(ByVal employeeId As Integer, ByVal planningName As String, ByVal allDay As Boolean, ByVal startMinute As Integer, ByVal endMinute As Integer, ByVal timeTypeId As Integer, ByVal dateInterval() As Date) As Boolean Implements ServiceSpec.IWebServiceContract.AddPlanning
            Return MyBase.Channel.AddPlanning(employeeId, planningName, allDay, startMinute, endMinute, timeTypeId, dateInterval)
        End Function
        
        Public Function GetDateRange(ByVal dateList() As Date) As ServiceSpec.WSElement Implements ServiceSpec.IWebServiceContract.GetDateRange
            Return MyBase.Channel.GetDateRange(dateList)
        End Function
    End Class
End Namespace
