//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5448
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.5448.
// 
#pragma warning disable 1591

namespace ServicesProxy.rhdesa {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultasSoap", Namespace="http://rhpro.com.ar/")]
    public partial class Consultas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VersionWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback VersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback PatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback MensajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback BannerOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModulosOperationCompleted;
        
        private System.Threading.SendOrPostCallback MRUOperationCompleted;
        
        private System.Threading.SendOrPostCallback PagPieOperationCompleted;
        
        private System.Threading.SendOrPostCallback comboBaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambiarPassOperationCompleted;
        
        private System.Threading.SendOrPostCallback PadreOperationCompleted;
        
        private System.Threading.SendOrPostCallback HijosOperationCompleted;
        
        private System.Threading.SendOrPostCallback DatosEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback AsignarPadreOperationCompleted;
        
        private System.Threading.SendOrPostCallback AsignarHijoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarHijoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarPadreOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SgtEmplOperationCompleted;
        
        private System.Threading.SendOrPostCallback AntEmplOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstadoPostulanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback TablaPlanaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ComboBanderasMIOperationCompleted;
        
        private System.Threading.SendOrPostCallback constrOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_DataTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_DataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_Traduccion_ModuloOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Consultas() {
            this.Url = global::ServicesProxy.Properties.Settings.Default.ServicesProxy_rhdesa_Consultas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VersionWSCompletedEventHandler VersionWSCompleted;
        
        /// <remarks/>
        public event VersionCompletedEventHandler VersionCompleted;
        
        /// <remarks/>
        public event PatchCompletedEventHandler PatchCompleted;
        
        /// <remarks/>
        public event LinkCompletedEventHandler LinkCompleted;
        
        /// <remarks/>
        public event MensajeCompletedEventHandler MensajeCompleted;
        
        /// <remarks/>
        public event BannerCompletedEventHandler BannerCompleted;
        
        /// <remarks/>
        public event ModulosCompletedEventHandler ModulosCompleted;
        
        /// <remarks/>
        public event MRUCompletedEventHandler MRUCompleted;
        
        /// <remarks/>
        public event PagPieCompletedEventHandler PagPieCompleted;
        
        /// <remarks/>
        public event comboBaseCompletedEventHandler comboBaseCompleted;
        
        /// <remarks/>
        public event SearchCompletedEventHandler SearchCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event CambiarPassCompletedEventHandler CambiarPassCompleted;
        
        /// <remarks/>
        public event PadreCompletedEventHandler PadreCompleted;
        
        /// <remarks/>
        public event HijosCompletedEventHandler HijosCompleted;
        
        /// <remarks/>
        public event DatosEmpCompletedEventHandler DatosEmpCompleted;
        
        /// <remarks/>
        public event AsignarPadreCompletedEventHandler AsignarPadreCompleted;
        
        /// <remarks/>
        public event AsignarHijoCompletedEventHandler AsignarHijoCompleted;
        
        /// <remarks/>
        public event BorrarHijoCompletedEventHandler BorrarHijoCompleted;
        
        /// <remarks/>
        public event BorrarPadreCompletedEventHandler BorrarPadreCompleted;
        
        /// <remarks/>
        public event BuscarEmpleadoCompletedEventHandler BuscarEmpleadoCompleted;
        
        /// <remarks/>
        public event SgtEmplCompletedEventHandler SgtEmplCompleted;
        
        /// <remarks/>
        public event AntEmplCompletedEventHandler AntEmplCompleted;
        
        /// <remarks/>
        public event EstadoPostulanteCompletedEventHandler EstadoPostulanteCompleted;
        
        /// <remarks/>
        public event TablaPlanaCompletedEventHandler TablaPlanaCompleted;
        
        /// <remarks/>
        public event ComboBanderasMICompletedEventHandler ComboBanderasMICompleted;
        
        /// <remarks/>
        public event constrCompletedEventHandler constrCompleted;
        
        /// <remarks/>
        public event get_DataTableCompletedEventHandler get_DataTableCompleted;
        
        /// <remarks/>
        public event get_DataSetCompletedEventHandler get_DataSetCompleted;
        
        /// <remarks/>
        public event get_Traduccion_ModuloCompletedEventHandler get_Traduccion_ModuloCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/VersionWS", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VersionWS() {
            object[] results = this.Invoke("VersionWS", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionWSAsync() {
            this.VersionWSAsync(null);
        }
        
        /// <remarks/>
        public void VersionWSAsync(object userState) {
            if ((this.VersionWSOperationCompleted == null)) {
                this.VersionWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionWSOperationCompleted);
            }
            this.InvokeAsync("VersionWS", new object[0], this.VersionWSOperationCompleted, userState);
        }
        
        private void OnVersionWSOperationCompleted(object arg) {
            if ((this.VersionWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionWSCompleted(this, new VersionWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/Version", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Version(string Base, string Idioma) {
            object[] results = this.Invoke("Version", new object[] {
                        Base,
                        Idioma});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionAsync(string Base, string Idioma) {
            this.VersionAsync(Base, Idioma, null);
        }
        
        /// <remarks/>
        public void VersionAsync(string Base, string Idioma, object userState) {
            if ((this.VersionOperationCompleted == null)) {
                this.VersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionOperationCompleted);
            }
            this.InvokeAsync("Version", new object[] {
                        Base,
                        Idioma}, this.VersionOperationCompleted, userState);
        }
        
        private void OnVersionOperationCompleted(object arg) {
            if ((this.VersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionCompleted(this, new VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/Patch", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Patch(string Base, string Idioma) {
            object[] results = this.Invoke("Patch", new object[] {
                        Base,
                        Idioma});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PatchAsync(string Base, string Idioma) {
            this.PatchAsync(Base, Idioma, null);
        }
        
        /// <remarks/>
        public void PatchAsync(string Base, string Idioma, object userState) {
            if ((this.PatchOperationCompleted == null)) {
                this.PatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPatchOperationCompleted);
            }
            this.InvokeAsync("Patch", new object[] {
                        Base,
                        Idioma}, this.PatchOperationCompleted, userState);
        }
        
        private void OnPatchOperationCompleted(object arg) {
            if ((this.PatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PatchCompleted(this, new PatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/Link", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Link(string Usuario, string Base, string Idioma) {
            object[] results = this.Invoke("Link", new object[] {
                        Usuario,
                        Base,
                        Idioma});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LinkAsync(string Usuario, string Base, string Idioma) {
            this.LinkAsync(Usuario, Base, Idioma, null);
        }
        
        /// <remarks/>
        public void LinkAsync(string Usuario, string Base, string Idioma, object userState) {
            if ((this.LinkOperationCompleted == null)) {
                this.LinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkOperationCompleted);
            }
            this.InvokeAsync("Link", new object[] {
                        Usuario,
                        Base,
                        Idioma}, this.LinkOperationCompleted, userState);
        }
        
        private void OnLinkOperationCompleted(object arg) {
            if ((this.LinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkCompleted(this, new LinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/Mensaje", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Mensaje(string Base, string Idioma) {
            object[] results = this.Invoke("Mensaje", new object[] {
                        Base,
                        Idioma});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MensajeAsync(string Base, string Idioma) {
            this.MensajeAsync(Base, Idioma, null);
        }
        
        /// <remarks/>
        public void MensajeAsync(string Base, string Idioma, object userState) {
            if ((this.MensajeOperationCompleted == null)) {
                this.MensajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMensajeOperationCompleted);
            }
            this.InvokeAsync("Mensaje", new object[] {
                        Base,
                        Idioma}, this.MensajeOperationCompleted, userState);
        }
        
        private void OnMensajeOperationCompleted(object arg) {
            if ((this.MensajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MensajeCompleted(this, new MensajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/Banner", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Banner(string Base, string Idioma) {
            object[] results = this.Invoke("Banner", new object[] {
                        Base,
                        Idioma});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BannerAsync(string Base, string Idioma) {
            this.BannerAsync(Base, Idioma, null);
        }
        
        /// <remarks/>
        public void BannerAsync(string Base, string Idioma, object userState) {
            if ((this.BannerOperationCompleted == null)) {
                this.BannerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBannerOperationCompleted);
            }
            this.InvokeAsync("Banner", new object[] {
                        Base,
                        Idioma}, this.BannerOperationCompleted, userState);
        }
        
        private void OnBannerOperationCompleted(object arg) {
            if ((this.BannerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BannerCompleted(this, new BannerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/Modulos", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Modulos(string Usuario, string Base, string Idioma) {
            object[] results = this.Invoke("Modulos", new object[] {
                        Usuario,
                        Base,
                        Idioma});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ModulosAsync(string Usuario, string Base, string Idioma) {
            this.ModulosAsync(Usuario, Base, Idioma, null);
        }
        
        /// <remarks/>
        public void ModulosAsync(string Usuario, string Base, string Idioma, object userState) {
            if ((this.ModulosOperationCompleted == null)) {
                this.ModulosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModulosOperationCompleted);
            }
            this.InvokeAsync("Modulos", new object[] {
                        Usuario,
                        Base,
                        Idioma}, this.ModulosOperationCompleted, userState);
        }
        
        private void OnModulosOperationCompleted(object arg) {
            if ((this.ModulosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModulosCompleted(this, new ModulosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/MRU", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MRU(string Usuario, int Cant, string Base, string Idioma) {
            object[] results = this.Invoke("MRU", new object[] {
                        Usuario,
                        Cant,
                        Base,
                        Idioma});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MRUAsync(string Usuario, int Cant, string Base, string Idioma) {
            this.MRUAsync(Usuario, Cant, Base, Idioma, null);
        }
        
        /// <remarks/>
        public void MRUAsync(string Usuario, int Cant, string Base, string Idioma, object userState) {
            if ((this.MRUOperationCompleted == null)) {
                this.MRUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMRUOperationCompleted);
            }
            this.InvokeAsync("MRU", new object[] {
                        Usuario,
                        Cant,
                        Base,
                        Idioma}, this.MRUOperationCompleted, userState);
        }
        
        private void OnMRUOperationCompleted(object arg) {
            if ((this.MRUCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MRUCompleted(this, new MRUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/PagPie", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PagPie(string Usuario, string Base, string Idioma) {
            object[] results = this.Invoke("PagPie", new object[] {
                        Usuario,
                        Base,
                        Idioma});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PagPieAsync(string Usuario, string Base, string Idioma) {
            this.PagPieAsync(Usuario, Base, Idioma, null);
        }
        
        /// <remarks/>
        public void PagPieAsync(string Usuario, string Base, string Idioma, object userState) {
            if ((this.PagPieOperationCompleted == null)) {
                this.PagPieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPagPieOperationCompleted);
            }
            this.InvokeAsync("PagPie", new object[] {
                        Usuario,
                        Base,
                        Idioma}, this.PagPieOperationCompleted, userState);
        }
        
        private void OnPagPieOperationCompleted(object arg) {
            if ((this.PagPieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PagPieCompleted(this, new PagPieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/comboBase", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable comboBase() {
            object[] results = this.Invoke("comboBase", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void comboBaseAsync() {
            this.comboBaseAsync(null);
        }
        
        /// <remarks/>
        public void comboBaseAsync(object userState) {
            if ((this.comboBaseOperationCompleted == null)) {
                this.comboBaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OncomboBaseOperationCompleted);
            }
            this.InvokeAsync("comboBase", new object[0], this.comboBaseOperationCompleted, userState);
        }
        
        private void OncomboBaseOperationCompleted(object arg) {
            if ((this.comboBaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.comboBaseCompleted(this, new comboBaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/Search", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Search(string Usuario, string Palabra, string Base, string Idioma) {
            object[] results = this.Invoke("Search", new object[] {
                        Usuario,
                        Palabra,
                        Base,
                        Idioma});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SearchAsync(string Usuario, string Palabra, string Base, string Idioma) {
            this.SearchAsync(Usuario, Palabra, Base, Idioma, null);
        }
        
        /// <remarks/>
        public void SearchAsync(string Usuario, string Palabra, string Base, string Idioma, object userState) {
            if ((this.SearchOperationCompleted == null)) {
                this.SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOperationCompleted);
            }
            this.InvokeAsync("Search", new object[] {
                        Usuario,
                        Palabra,
                        Base,
                        Idioma}, this.SearchOperationCompleted, userState);
        }
        
        private void OnSearchOperationCompleted(object arg) {
            if ((this.SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCompleted(this, new SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/Login", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Login(string Usuario, string Pass, string SegNt, string Base, string Idioma) {
            object[] results = this.Invoke("Login", new object[] {
                        Usuario,
                        Pass,
                        SegNt,
                        Base,
                        Idioma});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string Usuario, string Pass, string SegNt, string Base, string Idioma) {
            this.LoginAsync(Usuario, Pass, SegNt, Base, Idioma, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string Usuario, string Pass, string SegNt, string Base, string Idioma, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        Usuario,
                        Pass,
                        SegNt,
                        Base,
                        Idioma}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/CambiarPass", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CambiarPass(string Usuario, string PassOld, string PassNew, string PassConfirm, string Base, string Idioma) {
            object[] results = this.Invoke("CambiarPass", new object[] {
                        Usuario,
                        PassOld,
                        PassNew,
                        PassConfirm,
                        Base,
                        Idioma});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CambiarPassAsync(string Usuario, string PassOld, string PassNew, string PassConfirm, string Base, string Idioma) {
            this.CambiarPassAsync(Usuario, PassOld, PassNew, PassConfirm, Base, Idioma, null);
        }
        
        /// <remarks/>
        public void CambiarPassAsync(string Usuario, string PassOld, string PassNew, string PassConfirm, string Base, string Idioma, object userState) {
            if ((this.CambiarPassOperationCompleted == null)) {
                this.CambiarPassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambiarPassOperationCompleted);
            }
            this.InvokeAsync("CambiarPass", new object[] {
                        Usuario,
                        PassOld,
                        PassNew,
                        PassConfirm,
                        Base,
                        Idioma}, this.CambiarPassOperationCompleted, userState);
        }
        
        private void OnCambiarPassOperationCompleted(object arg) {
            if ((this.CambiarPassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambiarPassCompleted(this, new CambiarPassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/Padre", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long Padre(long CodEmp, int Base) {
            object[] results = this.Invoke("Padre", new object[] {
                        CodEmp,
                        Base});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void PadreAsync(long CodEmp, int Base) {
            this.PadreAsync(CodEmp, Base, null);
        }
        
        /// <remarks/>
        public void PadreAsync(long CodEmp, int Base, object userState) {
            if ((this.PadreOperationCompleted == null)) {
                this.PadreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPadreOperationCompleted);
            }
            this.InvokeAsync("Padre", new object[] {
                        CodEmp,
                        Base}, this.PadreOperationCompleted, userState);
        }
        
        private void OnPadreOperationCompleted(object arg) {
            if ((this.PadreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PadreCompleted(this, new PadreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/Hijos", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Hijos(long CodEmp, int Base) {
            object[] results = this.Invoke("Hijos", new object[] {
                        CodEmp,
                        Base});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HijosAsync(long CodEmp, int Base) {
            this.HijosAsync(CodEmp, Base, null);
        }
        
        /// <remarks/>
        public void HijosAsync(long CodEmp, int Base, object userState) {
            if ((this.HijosOperationCompleted == null)) {
                this.HijosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHijosOperationCompleted);
            }
            this.InvokeAsync("Hijos", new object[] {
                        CodEmp,
                        Base}, this.HijosOperationCompleted, userState);
        }
        
        private void OnHijosOperationCompleted(object arg) {
            if ((this.HijosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HijosCompleted(this, new HijosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/DatosEmp", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DatosEmp(long CodEmp, int Base) {
            object[] results = this.Invoke("DatosEmp", new object[] {
                        CodEmp,
                        Base});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DatosEmpAsync(long CodEmp, int Base) {
            this.DatosEmpAsync(CodEmp, Base, null);
        }
        
        /// <remarks/>
        public void DatosEmpAsync(long CodEmp, int Base, object userState) {
            if ((this.DatosEmpOperationCompleted == null)) {
                this.DatosEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDatosEmpOperationCompleted);
            }
            this.InvokeAsync("DatosEmp", new object[] {
                        CodEmp,
                        Base}, this.DatosEmpOperationCompleted, userState);
        }
        
        private void OnDatosEmpOperationCompleted(object arg) {
            if ((this.DatosEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DatosEmpCompleted(this, new DatosEmpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/AsignarPadre", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AsignarPadre(long CodPadre, long CodHijo, int Base) {
            object[] results = this.Invoke("AsignarPadre", new object[] {
                        CodPadre,
                        CodHijo,
                        Base});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AsignarPadreAsync(long CodPadre, long CodHijo, int Base) {
            this.AsignarPadreAsync(CodPadre, CodHijo, Base, null);
        }
        
        /// <remarks/>
        public void AsignarPadreAsync(long CodPadre, long CodHijo, int Base, object userState) {
            if ((this.AsignarPadreOperationCompleted == null)) {
                this.AsignarPadreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAsignarPadreOperationCompleted);
            }
            this.InvokeAsync("AsignarPadre", new object[] {
                        CodPadre,
                        CodHijo,
                        Base}, this.AsignarPadreOperationCompleted, userState);
        }
        
        private void OnAsignarPadreOperationCompleted(object arg) {
            if ((this.AsignarPadreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AsignarPadreCompleted(this, new AsignarPadreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/AsignarHijo", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AsignarHijo(long CodHijo, long CodPadre, int Base) {
            object[] results = this.Invoke("AsignarHijo", new object[] {
                        CodHijo,
                        CodPadre,
                        Base});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AsignarHijoAsync(long CodHijo, long CodPadre, int Base) {
            this.AsignarHijoAsync(CodHijo, CodPadre, Base, null);
        }
        
        /// <remarks/>
        public void AsignarHijoAsync(long CodHijo, long CodPadre, int Base, object userState) {
            if ((this.AsignarHijoOperationCompleted == null)) {
                this.AsignarHijoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAsignarHijoOperationCompleted);
            }
            this.InvokeAsync("AsignarHijo", new object[] {
                        CodHijo,
                        CodPadre,
                        Base}, this.AsignarHijoOperationCompleted, userState);
        }
        
        private void OnAsignarHijoOperationCompleted(object arg) {
            if ((this.AsignarHijoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AsignarHijoCompleted(this, new AsignarHijoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/BorrarHijo", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool BorrarHijo(long CodHijo, long CodPadre, int Base) {
            object[] results = this.Invoke("BorrarHijo", new object[] {
                        CodHijo,
                        CodPadre,
                        Base});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarHijoAsync(long CodHijo, long CodPadre, int Base) {
            this.BorrarHijoAsync(CodHijo, CodPadre, Base, null);
        }
        
        /// <remarks/>
        public void BorrarHijoAsync(long CodHijo, long CodPadre, int Base, object userState) {
            if ((this.BorrarHijoOperationCompleted == null)) {
                this.BorrarHijoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarHijoOperationCompleted);
            }
            this.InvokeAsync("BorrarHijo", new object[] {
                        CodHijo,
                        CodPadre,
                        Base}, this.BorrarHijoOperationCompleted, userState);
        }
        
        private void OnBorrarHijoOperationCompleted(object arg) {
            if ((this.BorrarHijoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarHijoCompleted(this, new BorrarHijoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/BorrarPadre", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool BorrarPadre(long CodHijo, long CodPadre, int Base) {
            object[] results = this.Invoke("BorrarPadre", new object[] {
                        CodHijo,
                        CodPadre,
                        Base});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarPadreAsync(long CodHijo, long CodPadre, int Base) {
            this.BorrarPadreAsync(CodHijo, CodPadre, Base, null);
        }
        
        /// <remarks/>
        public void BorrarPadreAsync(long CodHijo, long CodPadre, int Base, object userState) {
            if ((this.BorrarPadreOperationCompleted == null)) {
                this.BorrarPadreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarPadreOperationCompleted);
            }
            this.InvokeAsync("BorrarPadre", new object[] {
                        CodHijo,
                        CodPadre,
                        Base}, this.BorrarPadreOperationCompleted, userState);
        }
        
        private void OnBorrarPadreOperationCompleted(object arg) {
            if ((this.BorrarPadreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarPadreCompleted(this, new BorrarPadreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/BuscarEmpleado", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BuscarEmpleado(long Legajo, long Activo, int Base) {
            object[] results = this.Invoke("BuscarEmpleado", new object[] {
                        Legajo,
                        Activo,
                        Base});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEmpleadoAsync(long Legajo, long Activo, int Base) {
            this.BuscarEmpleadoAsync(Legajo, Activo, Base, null);
        }
        
        /// <remarks/>
        public void BuscarEmpleadoAsync(long Legajo, long Activo, int Base, object userState) {
            if ((this.BuscarEmpleadoOperationCompleted == null)) {
                this.BuscarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("BuscarEmpleado", new object[] {
                        Legajo,
                        Activo,
                        Base}, this.BuscarEmpleadoOperationCompleted, userState);
        }
        
        private void OnBuscarEmpleadoOperationCompleted(object arg) {
            if ((this.BuscarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEmpleadoCompleted(this, new BuscarEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/SgtEmpl", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SgtEmpl(long Legajo, long Activo, int Base) {
            object[] results = this.Invoke("SgtEmpl", new object[] {
                        Legajo,
                        Activo,
                        Base});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SgtEmplAsync(long Legajo, long Activo, int Base) {
            this.SgtEmplAsync(Legajo, Activo, Base, null);
        }
        
        /// <remarks/>
        public void SgtEmplAsync(long Legajo, long Activo, int Base, object userState) {
            if ((this.SgtEmplOperationCompleted == null)) {
                this.SgtEmplOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSgtEmplOperationCompleted);
            }
            this.InvokeAsync("SgtEmpl", new object[] {
                        Legajo,
                        Activo,
                        Base}, this.SgtEmplOperationCompleted, userState);
        }
        
        private void OnSgtEmplOperationCompleted(object arg) {
            if ((this.SgtEmplCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SgtEmplCompleted(this, new SgtEmplCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/AntEmpl", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AntEmpl(long Legajo, long Activo, int Base) {
            object[] results = this.Invoke("AntEmpl", new object[] {
                        Legajo,
                        Activo,
                        Base});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void AntEmplAsync(long Legajo, long Activo, int Base) {
            this.AntEmplAsync(Legajo, Activo, Base, null);
        }
        
        /// <remarks/>
        public void AntEmplAsync(long Legajo, long Activo, int Base, object userState) {
            if ((this.AntEmplOperationCompleted == null)) {
                this.AntEmplOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAntEmplOperationCompleted);
            }
            this.InvokeAsync("AntEmpl", new object[] {
                        Legajo,
                        Activo,
                        Base}, this.AntEmplOperationCompleted, userState);
        }
        
        private void OnAntEmplOperationCompleted(object arg) {
            if ((this.AntEmplCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AntEmplCompleted(this, new AntEmplCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/EstadoPostulante", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable EstadoPostulante(int tipoDoc, string Doc, int Sexo, string Base) {
            object[] results = this.Invoke("EstadoPostulante", new object[] {
                        tipoDoc,
                        Doc,
                        Sexo,
                        Base});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void EstadoPostulanteAsync(int tipoDoc, string Doc, int Sexo, string Base) {
            this.EstadoPostulanteAsync(tipoDoc, Doc, Sexo, Base, null);
        }
        
        /// <remarks/>
        public void EstadoPostulanteAsync(int tipoDoc, string Doc, int Sexo, string Base, object userState) {
            if ((this.EstadoPostulanteOperationCompleted == null)) {
                this.EstadoPostulanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstadoPostulanteOperationCompleted);
            }
            this.InvokeAsync("EstadoPostulante", new object[] {
                        tipoDoc,
                        Doc,
                        Sexo,
                        Base}, this.EstadoPostulanteOperationCompleted, userState);
        }
        
        private void OnEstadoPostulanteOperationCompleted(object arg) {
            if ((this.EstadoPostulanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstadoPostulanteCompleted(this, new EstadoPostulanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/TablaPlana", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TablaPlana(string Tabla, string Base) {
            object[] results = this.Invoke("TablaPlana", new object[] {
                        Tabla,
                        Base});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TablaPlanaAsync(string Tabla, string Base) {
            this.TablaPlanaAsync(Tabla, Base, null);
        }
        
        /// <remarks/>
        public void TablaPlanaAsync(string Tabla, string Base, object userState) {
            if ((this.TablaPlanaOperationCompleted == null)) {
                this.TablaPlanaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTablaPlanaOperationCompleted);
            }
            this.InvokeAsync("TablaPlana", new object[] {
                        Tabla,
                        Base}, this.TablaPlanaOperationCompleted, userState);
        }
        
        private void OnTablaPlanaOperationCompleted(object arg) {
            if ((this.TablaPlanaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TablaPlanaCompleted(this, new TablaPlanaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/ComboBanderasMI", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ComboBanderasMI(int Base) {
            object[] results = this.Invoke("ComboBanderasMI", new object[] {
                        Base});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ComboBanderasMIAsync(int Base) {
            this.ComboBanderasMIAsync(Base, null);
        }
        
        /// <remarks/>
        public void ComboBanderasMIAsync(int Base, object userState) {
            if ((this.ComboBanderasMIOperationCompleted == null)) {
                this.ComboBanderasMIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnComboBanderasMIOperationCompleted);
            }
            this.InvokeAsync("ComboBanderasMI", new object[] {
                        Base}, this.ComboBanderasMIOperationCompleted, userState);
        }
        
        private void OnComboBanderasMIOperationCompleted(object arg) {
            if ((this.ComboBanderasMICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ComboBanderasMICompleted(this, new ComboBanderasMICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/constr", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string constr(string NroBase) {
            object[] results = this.Invoke("constr", new object[] {
                        NroBase});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void constrAsync(string NroBase) {
            this.constrAsync(NroBase, null);
        }
        
        /// <remarks/>
        public void constrAsync(string NroBase, object userState) {
            if ((this.constrOperationCompleted == null)) {
                this.constrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconstrOperationCompleted);
            }
            this.InvokeAsync("constr", new object[] {
                        NroBase}, this.constrOperationCompleted, userState);
        }
        
        private void OnconstrOperationCompleted(object arg) {
            if ((this.constrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.constrCompleted(this, new constrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/get_DataTable", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable get_DataTable(string sql, string NroBase) {
            object[] results = this.Invoke("get_DataTable", new object[] {
                        sql,
                        NroBase});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void get_DataTableAsync(string sql, string NroBase) {
            this.get_DataTableAsync(sql, NroBase, null);
        }
        
        /// <remarks/>
        public void get_DataTableAsync(string sql, string NroBase, object userState) {
            if ((this.get_DataTableOperationCompleted == null)) {
                this.get_DataTableOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_DataTableOperationCompleted);
            }
            this.InvokeAsync("get_DataTable", new object[] {
                        sql,
                        NroBase}, this.get_DataTableOperationCompleted, userState);
        }
        
        private void Onget_DataTableOperationCompleted(object arg) {
            if ((this.get_DataTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_DataTableCompleted(this, new get_DataTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/get_DataSet", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet get_DataSet(string sql, string NroBase) {
            object[] results = this.Invoke("get_DataSet", new object[] {
                        sql,
                        NroBase});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void get_DataSetAsync(string sql, string NroBase) {
            this.get_DataSetAsync(sql, NroBase, null);
        }
        
        /// <remarks/>
        public void get_DataSetAsync(string sql, string NroBase, object userState) {
            if ((this.get_DataSetOperationCompleted == null)) {
                this.get_DataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_DataSetOperationCompleted);
            }
            this.InvokeAsync("get_DataSet", new object[] {
                        sql,
                        NroBase}, this.get_DataSetOperationCompleted, userState);
        }
        
        private void Onget_DataSetOperationCompleted(object arg) {
            if ((this.get_DataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_DataSetCompleted(this, new get_DataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rhpro.com.ar/get_Traduccion_Modulo", RequestNamespace="http://rhpro.com.ar/", ResponseNamespace="http://rhpro.com.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable get_Traduccion_Modulo(string EtiqLenguaje, string Etiqueta, string NroBase) {
            object[] results = this.Invoke("get_Traduccion_Modulo", new object[] {
                        EtiqLenguaje,
                        Etiqueta,
                        NroBase});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void get_Traduccion_ModuloAsync(string EtiqLenguaje, string Etiqueta, string NroBase) {
            this.get_Traduccion_ModuloAsync(EtiqLenguaje, Etiqueta, NroBase, null);
        }
        
        /// <remarks/>
        public void get_Traduccion_ModuloAsync(string EtiqLenguaje, string Etiqueta, string NroBase, object userState) {
            if ((this.get_Traduccion_ModuloOperationCompleted == null)) {
                this.get_Traduccion_ModuloOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_Traduccion_ModuloOperationCompleted);
            }
            this.InvokeAsync("get_Traduccion_Modulo", new object[] {
                        EtiqLenguaje,
                        Etiqueta,
                        NroBase}, this.get_Traduccion_ModuloOperationCompleted, userState);
        }
        
        private void Onget_Traduccion_ModuloOperationCompleted(object arg) {
            if ((this.get_Traduccion_ModuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_Traduccion_ModuloCompleted(this, new get_Traduccion_ModuloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void VersionWSCompletedEventHandler(object sender, VersionWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void VersionCompletedEventHandler(object sender, VersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void PatchCompletedEventHandler(object sender, PatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void LinkCompletedEventHandler(object sender, LinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void MensajeCompletedEventHandler(object sender, MensajeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MensajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MensajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void BannerCompletedEventHandler(object sender, BannerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BannerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BannerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void ModulosCompletedEventHandler(object sender, ModulosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModulosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModulosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void MRUCompletedEventHandler(object sender, MRUCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MRUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MRUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void PagPieCompletedEventHandler(object sender, PagPieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PagPieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PagPieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void comboBaseCompletedEventHandler(object sender, comboBaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class comboBaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal comboBaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SearchCompletedEventHandler(object sender, SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void CambiarPassCompletedEventHandler(object sender, CambiarPassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CambiarPassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CambiarPassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void PadreCompletedEventHandler(object sender, PadreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PadreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PadreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void HijosCompletedEventHandler(object sender, HijosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HijosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HijosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void DatosEmpCompletedEventHandler(object sender, DatosEmpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatosEmpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DatosEmpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void AsignarPadreCompletedEventHandler(object sender, AsignarPadreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AsignarPadreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AsignarPadreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void AsignarHijoCompletedEventHandler(object sender, AsignarHijoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AsignarHijoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AsignarHijoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void BorrarHijoCompletedEventHandler(object sender, BorrarHijoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarHijoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarHijoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void BorrarPadreCompletedEventHandler(object sender, BorrarPadreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarPadreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarPadreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void BuscarEmpleadoCompletedEventHandler(object sender, BuscarEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SgtEmplCompletedEventHandler(object sender, SgtEmplCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SgtEmplCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SgtEmplCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void AntEmplCompletedEventHandler(object sender, AntEmplCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AntEmplCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AntEmplCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void EstadoPostulanteCompletedEventHandler(object sender, EstadoPostulanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstadoPostulanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstadoPostulanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void TablaPlanaCompletedEventHandler(object sender, TablaPlanaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TablaPlanaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TablaPlanaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void ComboBanderasMICompletedEventHandler(object sender, ComboBanderasMICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComboBanderasMICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ComboBanderasMICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void constrCompletedEventHandler(object sender, constrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class constrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal constrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void get_DataTableCompletedEventHandler(object sender, get_DataTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_DataTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_DataTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void get_DataSetCompletedEventHandler(object sender, get_DataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_DataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_DataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void get_Traduccion_ModuloCompletedEventHandler(object sender, get_Traduccion_ModuloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_Traduccion_ModuloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_Traduccion_ModuloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591