'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5448
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Web.Services.WebServiceBindingAttribute(Name:="ServiceMovimientosSoap", [Namespace]:="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos")> _
Partial Public Class ServiceMovimientos
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

    Private wsListarMovimientosOperationCompleted As System.Threading.SendOrPostCallback

    '''<remarks/>
    Public Sub New()
        MyBase.New()
        Me.Url = "http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos.asmx"
    End Sub

    '''<remarks/>
    Public Event wsListarMovimientosCompleted As wsListarMovimientosCompletedEventHandler

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientos", RequestNamespace:="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos", ResponseNamespace:="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
    Public Function wsListarMovimientos(ByVal idEmpresa As Integer, ByVal password As String, ByVal Legajo As String, ByVal fechaDesde As String, ByVal fechaHasta As String, ByVal marcaExporta As Integer, ByVal marcaMov As Integer, ByVal TipoSalida As Integer) As System.Data.DataSet
        Dim results() As Object = Me.Invoke("wsListarMovimientos", New Object() {idEmpresa, password, Legajo, fechaDesde, fechaHasta, marcaExporta, marcaMov, TipoSalida})
        Return CType(results(0), System.Data.DataSet)
    End Function

    '''<remarks/>
    Public Function BeginwsListarMovimientos(ByVal idEmpresa As Integer, ByVal password As String, ByVal Legajo As String, ByVal fechaDesde As String, ByVal fechaHasta As String, ByVal marcaExporta As Integer, ByVal marcaMov As Integer, ByVal TipoSalida As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("wsListarMovimientos", New Object() {idEmpresa, password, Legajo, fechaDesde, fechaHasta, marcaExporta, marcaMov, TipoSalida}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function EndwsListarMovimientos(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), System.Data.DataSet)
    End Function

    '''<remarks/>
    Public Overloads Sub wsListarMovimientosAsync(ByVal idEmpresa As Integer, ByVal password As String, ByVal Legajo As String, ByVal fechaDesde As String, ByVal fechaHasta As String, ByVal marcaExporta As Integer, ByVal marcaMov As Integer, ByVal TipoSalida As Integer)
        Me.wsListarMovimientosAsync(idEmpresa, password, Legajo, fechaDesde, fechaHasta, marcaExporta, marcaMov, TipoSalida, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub wsListarMovimientosAsync(ByVal idEmpresa As Integer, ByVal password As String, ByVal Legajo As String, ByVal fechaDesde As String, ByVal fechaHasta As String, ByVal marcaExporta As Integer, ByVal marcaMov As Integer, ByVal TipoSalida As Integer, ByVal userState As Object)
        If (Me.wsListarMovimientosOperationCompleted Is Nothing) Then
            Me.wsListarMovimientosOperationCompleted = AddressOf Me.OnwsListarMovimientosOperationCompleted
        End If
        Me.InvokeAsync("wsListarMovimientos", New Object() {idEmpresa, password, Legajo, fechaDesde, fechaHasta, marcaExporta, marcaMov, TipoSalida}, Me.wsListarMovimientosOperationCompleted, userState)
    End Sub

    Private Sub OnwsListarMovimientosOperationCompleted(ByVal arg As Object)
        If (Not (Me.wsListarMovimientosCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent wsListarMovimientosCompleted(Me, New wsListarMovimientosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")>  _
Public Delegate Sub wsListarMovimientosCompletedEventHandler(ByVal sender As Object, ByVal e As wsListarMovimientosCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class wsListarMovimientosCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As System.Data.DataSet
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),System.Data.DataSet)
        End Get
    End Property
End Class
